# Generated by Django 3.2.9 on 2022-01-31 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplierID', models.CharField(max_length=100)),
                ('supplierName', models.CharField(max_length=100)),
                ('brand', models.TextField()),
                ('partCategory', models.CharField(max_length=100)),
                ('vehicleType', models.CharField(max_length=100)),
                ('billingMethod', models.CharField(max_length=100)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('transactionTerm', models.CharField(max_length=100)),
                ('streetAddr', models.CharField(max_length=100)),
                ('postalCode', models.IntegerField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('totalSupPts', models.FloatField()),
            ],
        ),
    ]
