# Generated by Django 3.2.9 on 2021-12-16 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNo', models.CharField(max_length=15)),
                ('dealerID', models.CharField(max_length=15)),
                ('adminID', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=30)),
                ('streetAddr', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=25)),
                ('postalCode', models.CharField(max_length=5)),
                ('state', models.CharField(max_length=20)),
            ],
        ),
    ]
