# Generated by Django 3.2.9 on 2022-01-04 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('partno', models.CharField(db_column='partNo', max_length=15, primary_key=True, serialize=False)),
                ('partname', models.CharField(blank=True, db_column='partName', max_length=40, null=True)),
                ('partcategory', models.CharField(blank=True, db_column='partCategory', max_length=30, null=True)),
                ('partyear', models.DateField(blank=True, db_column='partYear', null=True)),
                ('quality', models.CharField(blank=True, max_length=10, null=True)),
                ('unitprice', models.DecimalField(blank=True, db_column='unitPrice', decimal_places=2, max_digits=10, null=True)),
                ('stock', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'part',
                'managed': False,
            },
        ),
    ]
