# Generated by Django 3.2.9 on 2022-01-31 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyProfit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField(unique=True)),
                ('profit', models.FloatField()),
            ],
            options={
                'ordering': ['week'],
            },
        ),
    ]
