# Generated by Django 3.2.9 on 2022-01-31 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('percentage_value', models.FloatField()),
                ('invoiceNo', models.CharField(max_length=100)),
                ('paymentID', models.CharField(max_length=100)),
                ('orderID', models.CharField(max_length=100)),
                ('custPhone', models.CharField(max_length=100)),
                ('custAddr', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Markup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, null=True)),
                ('percentage_value', models.FloatField()),
            ],
        ),
    ]
