# Generated by Django 3.2.9 on 2022-01-31 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_invoice_markup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='category',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='percentage_value',
        ),
    ]
