# Generated by Django 3.2.9 on 2022-01-31 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20220131_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoiceDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='totalPayment',
            field=models.FloatField(null=True),
        ),
    ]
